//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuxion.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fuxion.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes.
        /// </summary>
        public static string Changes {
            get {
                return ResourceManager.GetString("Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity of type &apos;{0}&apos; called &apos;{1}&apos; will be added to &apos;{2}&apos;.
        /// </summary>
        public static string EntityWillBeAdded {
            get {
                return ResourceManager.GetString("EntityWillBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity of type &apos;{0}&apos; called &apos;{1}&apos; will be deleted from &apos;{2}&apos;.
        /// </summary>
        public static string EntityWillBeDeleted {
            get {
                return ResourceManager.GetString("EntityWillBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity of type &apos;{0}&apos; called &apos;{1}&apos; will be ignored.
        /// </summary>
        public static string EntityWillBeIgnored {
            get {
                return ResourceManager.GetString("EntityWillBeIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity of type &apos;{0}&apos; called &apos;{1}&apos; will be updated on &apos;{2}&apos;.
        /// </summary>
        public static string EntityWillBeUpdated {
            get {
                return ResourceManager.GetString("EntityWillBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to millisecond.
        /// </summary>
        public static string millisecond {
            get {
                return ResourceManager.GetString("millisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliseconds.
        /// </summary>
        public static string milliseconds {
            get {
                return ResourceManager.GetString("milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        public static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        public static string months {
            get {
                return ResourceManager.GetString("months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; will be changed from &apos;{1}&apos; to &apos;{2}&apos;.
        /// </summary>
        public static string PropertyWillBeChanged {
            get {
                return ResourceManager.GetString("PropertyWillBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A relation with entity of type &apos;{0}&apos; called &apos;{1}&apos; will be added to &apos;{2}&apos;.
        /// </summary>
        public static string RelationWillBeAdded {
            get {
                return ResourceManager.GetString("RelationWillBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A relation with entity of type &apos;{0}&apos; called &apos;{1}&apos; will be deleted from &apos;{2}&apos;.
        /// </summary>
        public static string RelationWillBeDeleted {
            get {
                return ResourceManager.GetString("RelationWillBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A relation with entity of type &apos;{0}&apos; called &apos;{1}&apos; will be ignored.
        /// </summary>
        public static string RelationWillBeIgnored {
            get {
                return ResourceManager.GetString("RelationWillBeIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A relation with entity of type &apos;{0}&apos; called &apos;{1}&apos; will be updated to &apos;{2}&apos;.
        /// </summary>
        public static string RelationWillBeUpdated {
            get {
                return ResourceManager.GetString("RelationWillBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        public static string second {
            get {
                return ResourceManager.GetString("second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tick.
        /// </summary>
        public static string tick {
            get {
                return ResourceManager.GetString("tick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ticks.
        /// </summary>
        public static string ticks {
            get {
                return ResourceManager.GetString("ticks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        public static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string years {
            get {
                return ResourceManager.GetString("years", resourceCulture);
            }
        }
    }
}
