<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(CoreAndOldFrameworks)</TargetFrameworks>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Primitive\TestBool.cs" />
	  <Compile Remove="Primitive\TestByte.cs" />
	  <Compile Remove="Primitive\TestChar.cs" />
	  <Compile Remove="Primitive\TestDateTime.cs" />
	  <Compile Remove="Primitive\TestDecimal.cs" />
	  <Compile Remove="Primitive\TestDouble.cs" />
	  <Compile Remove="Primitive\TestFloat.cs" />
	  <Compile Remove="Primitive\TestGuid.cs" />
	  <Compile Remove="Primitive\TestInt.cs" />
	  <Compile Remove="Primitive\TestLong.cs" />
	  <Compile Remove="Primitive\TestNullableByte.cs" />
	  <Compile Remove="Primitive\TestNullableChar.cs" />
	  <Compile Remove="Primitive\TestNullableDateTime.cs" />
	  <Compile Remove="Primitive\TestNullableDecimal.cs" />
	  <Compile Remove="Primitive\TestNullableDouble.cs" />
	  <Compile Remove="Primitive\TestNullableFloat.cs" />
	  <Compile Remove="Primitive\TestNullableGuid.cs" />
	  <Compile Remove="Primitive\TestNullableInt.cs" />
	  <Compile Remove="Primitive\TestNullableLong.cs" />
	  <Compile Remove="Primitive\TestNullableSByte.cs" />
	  <Compile Remove="Primitive\TestNullableShort.cs" />
	  <Compile Remove="Primitive\TestNullableTimeSpan.cs" />
	  <Compile Remove="Primitive\TestNullableUInt.cs" />
	  <Compile Remove="Primitive\TestNullableULong.cs" />
	  <Compile Remove="Primitive\TestSByte.cs" />
	  <Compile Remove="Primitive\TestShort.cs" />
	  <Compile Remove="Primitive\TestString.cs" />
	  <Compile Remove="Primitive\TestTimeSpan.cs" />
	  <Compile Remove="Primitive\TestUInt.cs" />
	  <Compile Remove="Primitive\TestULong.cs" />
	  <Compile Remove="Primitive\TestUShort.cs" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="Primitive\TestBool.cs" />
	  <None Include="Primitive\TestByte.cs" />
	  <None Include="Primitive\TestChar.cs" />
	  <None Include="Primitive\TestDateTime.cs" />
	  <None Include="Primitive\TestDecimal.cs" />
	  <None Include="Primitive\TestDouble.cs" />
	  <None Include="Primitive\TestFloat.cs" />
	  <None Include="Primitive\TestGuid.cs" />
	  <None Include="Primitive\TestInt.cs" />
	  <None Include="Primitive\TestLong.cs" />
	  <None Include="Primitive\TestNullableByte.cs" />
	  <None Include="Primitive\TestNullableChar.cs" />
	  <None Include="Primitive\TestNullableDateTime.cs" />
	  <None Include="Primitive\TestNullableDecimal.cs" />
	  <None Include="Primitive\TestNullableDouble.cs" />
	  <None Include="Primitive\TestNullableFloat.cs" />
	  <None Include="Primitive\TestNullableGuid.cs" />
	  <None Include="Primitive\TestNullableInt.cs" />
	  <None Include="Primitive\TestNullableLong.cs" />
	  <None Include="Primitive\TestNullableSByte.cs" />
	  <None Include="Primitive\TestNullableShort.cs" />
	  <None Include="Primitive\TestNullableTimeSpan.cs" />
	  <None Include="Primitive\TestNullableUInt.cs" />
	  <None Include="Primitive\TestNullableULong.cs" />
	  <None Include="Primitive\TestSByte.cs" />
	  <None Include="Primitive\TestShort.cs" />
	  <None Include="Primitive\TestString.cs" />
	  <None Include="Primitive\TestTimeSpan.cs" />
	  <None Include="Primitive\TestUInt.cs" />
	  <None Include="Primitive\TestULong.cs" />
	  <None Include="Primitive\TestUShort.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="System.Private.Uri" />
		<PackageReference Include="Testcontainers.XunitV3" />
		<PackageReference Include="Testcontainers.Redis" />
		<PackageReference Include="Testcontainers.MsSql" />
		<PackageReference Include="Testcontainers.MongoDb" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Linq\Fuxion.Linq.csproj" />
		<ProjectReference Include="..\..\src\Xunit\Fuxion.Xunit.csproj" />
		<ProjectReference Include="..\..\src\Linq.CodeGenerator\Fuxion.Linq.CodeGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<ProjectReference Include="..\Dataset\Test.Dataset.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(IsCoreFrameworks)' == 'true'">
		<ProjectReference Include="..\Dataset.EntityFrameworkCore.SqlServer\Test.Dataset.EntityFrameworkCore.SqlServer.csproj" />
		<ProjectReference Include="..\Dataset.EntityFrameworkCore.MongoDB\Test.Dataset.EntityFrameworkCore.MongoDB.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(IsOldFrameworks)' == 'true'">
		<ProjectReference Include="..\Dataset.EntityFramework\Test.Dataset.EntityFramework.csproj" />
	</ItemGroup>

</Project>
