<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
		<CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
	</PropertyGroup>

	<ItemGroup>
		<PackageVersion Include="coverlet.collector" Version="10.0.0" />
		<PackageVersion Include="EntityFramework" Version="6.5.2" />
		<PackageVersion Include="Microsoft.AspNet.WebApi.Core" Version="5.3.0" />
		<PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" />
		<PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.3.0" />
		<PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0" />
		<PackageVersion Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
		<PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.203" />
		<PackageVersion Include="PolySharp" Version="1.15.0" />
		<PackageVersion Include="xunit.analyzers" Version="1.27.0" />
		<PackageVersion Include="xunit.v3" Version="3.2.2" />
		<PackageVersion Include="xunit.v3.assert" Version="3.2.2" />
		<PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
		<PackageVersion Include="MongoDB.EntityFrameworkCore" Version="10.0.1" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' != 'net10.0'">
		<PackageVersion Include="MongoDB.EntityFrameworkCore" Version="9.1.1" />
	</ItemGroup>

	<!-- Framework Packages -->
	<PropertyGroup>
		<NetStableVersion>10.0.7</NetStableVersion>
	</PropertyGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0'
			   Or '$(TargetFramework)' == 'net10.0-windows10.0.19041'
			   Or '$(TargetFramework)' == 'net9.0'
			   Or '$(TargetFramework)' == 'net9.0-windows10.0.19041'
			   Or '$(TargetFramework)' == 'net8.0'
			   Or '$(TargetFramework)' == 'net8.0-windows10.0.19041'
			   Or '$(TargetFramework)' == 'net472'
			   Or '$(TargetFramework)' == 'netstandard2.0'">
		<PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="$(NetStableVersion)" />
		<PackageVersion Include="Microsoft.Extensions.Logging.Configuration" Version="$(NetStableVersion)" />
		<PackageVersion Include="System.Drawing.Common" Version="$(NetStableVersion)" />
		<PackageVersion Include="System.Management" Version="$(NetStableVersion)" />
		<PackageVersion Include="System.Text.Json" Version="$(NetStableVersion)" />
	</ItemGroup>

	<!-- Entity Framework Core Packages -->
	<PropertyGroup>
		<EntityFrameworkCore10Version>10.0.7</EntityFrameworkCore10Version>
	</PropertyGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0'
			   Or '$(TargetFramework)' == 'net10.0-windows10.0.19041'">
		<PackageVersion Include="Microsoft.EntityFrameworkCore" Version="$(EntityFrameworkCore10Version)" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore.InMemory" Version="$(EntityFrameworkCore10Version)" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="$(EntityFrameworkCore10Version)" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="$(EntityFrameworkCore10Version)" />
	</ItemGroup>
	<PropertyGroup>
		<EntityFrameworkCore9Version>9.0.15</EntityFrameworkCore9Version>
	</PropertyGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0'
			   Or '$(TargetFramework)' == 'net9.0-windows10.0.19041'
			   Or '$(TargetFramework)' == 'net8.0'
			   Or '$(TargetFramework)' == 'net8.0-windows10.0.19041'
			   Or '$(TargetFramework)' == 'net472'
			   Or '$(TargetFramework)' == 'netstandard2.0'">
		<PackageVersion Include="Microsoft.EntityFrameworkCore" Version="$(EntityFrameworkCore9Version)" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore.InMemory" Version="$(EntityFrameworkCore9Version)" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="$(EntityFrameworkCore9Version)" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="$(EntityFrameworkCore9Version)" />
	</ItemGroup>
</Project>