//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuxion.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fuxion.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes.
        /// </summary>
        internal static string Changes {
            get {
                return ResourceManager.GetString("Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity of type &apos;{0}&apos; called &apos;{1}&apos; will be added to &apos;{2}&apos;.
        /// </summary>
        internal static string EntityWillBeAdded {
            get {
                return ResourceManager.GetString("EntityWillBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity of type &apos;{0}&apos; called &apos;{1}&apos; will be deleted from &apos;{2}&apos;.
        /// </summary>
        internal static string EntityWillBeDeleted {
            get {
                return ResourceManager.GetString("EntityWillBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity of type &apos;{0}&apos; called &apos;{1}&apos; will be ignored.
        /// </summary>
        internal static string EntityWillBeIgnored {
            get {
                return ResourceManager.GetString("EntityWillBeIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity of type &apos;{0}&apos; called &apos;{1}&apos; will be updated on &apos;{2}&apos;.
        /// </summary>
        internal static string EntityWillBeUpdated {
            get {
                return ResourceManager.GetString("EntityWillBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; will be changed from &apos;{1}&apos; to &apos;{2}&apos;.
        /// </summary>
        internal static string PropertyWillBeChanged {
            get {
                return ResourceManager.GetString("PropertyWillBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A relation with entity of type &apos;{0}&apos; called &apos;{1}&apos; will be added to &apos;{2}&apos;.
        /// </summary>
        internal static string RelationWillBeAdded {
            get {
                return ResourceManager.GetString("RelationWillBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A relation with entity of type &apos;{0}&apos; called &apos;{1}&apos; will be deleted from &apos;{2}&apos;.
        /// </summary>
        internal static string RelationWillBeDeleted {
            get {
                return ResourceManager.GetString("RelationWillBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A relation with entity of type &apos;{0}&apos; called &apos;{1}&apos; will be ignored.
        /// </summary>
        internal static string RelationWillBeIgnored {
            get {
                return ResourceManager.GetString("RelationWillBeIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A relation with entity of type &apos;{0}&apos; called &apos;{1}&apos; will be updated to &apos;{2}&apos;.
        /// </summary>
        internal static string RelationWillBeUpdated {
            get {
                return ResourceManager.GetString("RelationWillBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
