<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(DefaultFrameworks)</TargetFrameworks>
		<Title>Fuxion Analyzers Abstractions</Title>
		<PackageId>Fuxion.Analyzers.Abstractions</PackageId>
		<Description>Attribute definitions for Fuxion Roslyn analyzers. Use these attributes to mark members that require compile-time safety checks.</Description>
		<PackageTags>fuxion;analyzers;roslyn;csharp;attributes;abstractions</PackageTags>

		<!-- Packaging configuration -->
		<IsPackable>true</IsPackable>
		<IncludeBuildOutput>true</IncludeBuildOutput>
	</PropertyGroup>

</Project>
