<Project>
	
	<PropertyGroup>

		<!-- PROPS -->
		<Analyzers_Reference_Prop>$(MSBuildThisFileDirectory)props\Analyzers.Reference.props</Analyzers_Reference_Prop>
		<Core_Paths_Prop>$(MSBuildThisFileDirectory)props\Core.Paths.props</Core_Paths_Prop>
		<Nuget_Config_OpenSource_Prop>$(MSBuildThisFileDirectory)props\Nuget.Config.OpenSource.props</Nuget_Config_OpenSource_Prop>
		<Nuget_Pack_Analyzers_Prop>$(MSBuildThisFileDirectory)props\Nuget.Pack.Analyzers.props</Nuget_Pack_Analyzers_Prop>

		<!-- TARGETS -->
		<Nuget_Pack_Analyzers_Target>$(MSBuildThisFileDirectory)targets\Nuget.Pack.Analyzers.targets</Nuget_Pack_Analyzers_Target>
		
	</PropertyGroup>
	
</Project>