<Project>

	<Import Project="Nuget.Metadata.props" />
	
	<PropertyGroup>

		<!-- Project -->
		<PackageProjectUrl>https://fuxion.dev/</PackageProjectUrl>
		
		<!-- License -->
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>

		<!-- Repository -->
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<RepositoryUrl>https://github.com/osjimenez/Fuxion.git</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<!-- Symbols -->
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>

		<!-- SourceLink -->
		<SourceLinkCreate>true</SourceLinkCreate>
		<SourceLinkOriginUrl>https://github.com/osjimenez/Fuxion</SourceLinkOriginUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		
	</PropertyGroup>

	<ItemGroup>
		<!-- SourceLink package reference -->
		<PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All"/>
	</ItemGroup>
	
</Project>