<Project>

	<!-- The latest language features on netstandard and .NET Framework (from Project.Default.props of oss) -->
	<ItemGroup>
		<PackageReference Include="PolySharp" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
	</ItemGroup>

</Project>
