<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(StandardFramework)</TargetFramework>

		<!-- Required for code fix providers -->
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		
		<!-- Disable Nuget -->
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<!-- Reference to the analyzers project to share DiagnosticIds -->
		<ProjectReference Include="$(AnalyzersProjectPath)" PrivateAssets="all" />
	</ItemGroup>

</Project>
