namespace Fuxion.Xunit;

// OutputType=Exe is required by xunit.v3's own build validation for any project that references xunit.v3, even a
// library like this one with no [Fact] of its own. XunitAutoGeneratedEntryPoint is off so xunit does not wire its
// console runner as this assembly's entry point: this inert Main takes its place purely to satisfy the compiler,
// and is never meant to be invoked. Test.Responses.Shared does exactly the same for the same reason.
static class Program
{
	static void Main() { }
}
