<Project>

	<PropertyGroup>

		<!-- Project -->
		<PackageProjectUrl>https://fuxion.dev/</PackageProjectUrl>
		
		<!-- License -->
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>

		<!-- Repository -->
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<RepositoryUrl>https://github.com/osjimenez/Fuxion.git</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<!-- Symbols -->
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>

		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		
	</PropertyGroup>

	
</Project>