<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(CoreFrameworks)</TargetFrameworks>
		<Title>Fuxion Asp.Net Core</Title>
		<PackageId>Fuxion.AspNetCore</PackageId>
		<Description>Fuxion library for Asp.Net Core.</Description>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="$(FuxionProjectPath)" />
	</ItemGroup>

</Project>
