<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsTestProject>true</IsTestProject>
		<TargetFrameworks>$(CoreAndOldFrameworks)</TargetFrameworks>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="$(XunitProjectPath)" />
	</ItemGroup>

	<ItemGroup Condition="'$(IsOldFrameworks)' == 'true'">
		<Reference Include="System.Web" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Response.Accept.test.cs">
			<DependentUpon>Response.test.cs</DependentUpon>
		</Compile>
		<Compile Update="Response.Client.Binary.test.cs">
			<DependentUpon>Response.test.cs</DependentUpon>
		</Compile>
		<Compile Update="Response.Client.test.cs">
			<DependentUpon>Response.test.cs</DependentUpon>
		</Compile>
		<Compile Update="Response.EXT.test.cs">
			<DependentUpon>Response.test.cs</DependentUpon>
		</Compile>
		<Compile Update="Response.IOContent.test.cs">
			<DependentUpon>Response.test.cs</DependentUpon>
		</Compile>
		<Compile Update="Response.MediaTypes.test.cs">
			<DependentUpon>Response.test.cs</DependentUpon>
		</Compile>
		<Compile Update="Response.Naming.test.cs">
			<DependentUpon>Response.test.cs</DependentUpon>
		</Compile>
		<Compile Update="Response.Options.test.cs">
			<DependentUpon>Response.test.cs</DependentUpon>
		</Compile>
		<Compile Update="Response.ProblemDetails.test.cs">
			<DependentUpon>Response.test.cs</DependentUpon>
		</Compile>
		<Compile Update="Response.Serialization.test.cs">
			<DependentUpon>Response.test.cs</DependentUpon>
		</Compile>
		<Compile Update="Response.Wire.test.cs">
			<DependentUpon>Response.test.cs</DependentUpon>
		</Compile>
	</ItemGroup>

</Project>