name: .NET Core

on:
  push:
    branches: 
     - master
     - develop
     - 'release/**'

jobs:
  build:

    runs-on: windows-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.6
      with:
        versionSpec: '5.x.x'

    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.6

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x.x'

    - name: Install dependencies
      run: dotnet restore -p:RestoreUseSkipNonexistentTargets=false src/Fuxion-pack.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore -p:Version=${{ steps.gitversion.outputs.semVer }} src/Fuxion-pack.sln

#    - name: Run tests
#      run: dotnet test --configuration Release --no-restore --verbosity minimal src/Fuxion-pack.sln

    - name: Create packages
      run: dotnet pack --configuration Release --no-build --output nupkgs --no-build -p:PackageVersion=${{ steps.gitversion.outputs.semVer }} src/Fuxion-pack.sln

    - name: Publish to GitHub Packages
      if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/develop'
#      run: dotnet nuget push "nupkgs\*.nupkg" --source https://nuget.pkg.github.com/osjimenez/index.json --api-key ${{secrets.GITHUB_TOKEN}} --skip-duplicate
      run: dotnet nuget push "nupkgs\*.nupkg" --source "github"

    - name: Publish to NuGet.org
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
      run: dotnet nuget push "nupkgs\*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_ORG}} --skip-duplicate
    