name: .NET Core

on: 
  push:
    branches-ignore:
      - 'module/**'
      - 'feature/**'

jobs:
  build:

    runs-on: windows-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4.1.0
      with:
        versionSpec: '6.x'

    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v4.1.0
      with:
        useConfigFile: true

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.x.x'
        include-prerelease: true

    - name: Install dependencies
      run: dotnet restore -p:RestoreUseSkipNonexistentTargets=false solution/Fuxion-deploy.slnx

    - name: Build
      run: dotnet build --configuration Release --no-restore -p:Version=${{ steps.gitversion.outputs.semVer }} solution/Fuxion-deploy.slnx

#    - name: Run tests
#      run: dotnet test --configuration Release --no-restore --verbosity minimal solution/Fuxion-deploy.slnx

    - name: Create packages
      run: dotnet pack --configuration Release --no-build --output nupkgs -p:PackageVersion=${{ steps.gitversion.outputs.semVer }} solution/Fuxion-deploy.slnx

    - name: Publish to GitHub Packages
      if: github.ref != 'refs/heads/main'
      run: dotnet nuget push "nupkgs\*.*" --source https://nuget.pkg.github.com/OsJimenez/index.json --api-key ${{secrets.GITHUB_TOKEN}} --skip-duplicate

    - name: Publish to NuGet.org
      if: github.ref == 'refs/heads/main'
      run: dotnet nuget push "nupkgs\*.*" --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_ORG}} --skip-duplicate
    
