name: .NET Core

on:
  push:
    branches: [ feature/net5 ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

#    - name: Install dependencies
#      working-directory: src/core/fuxion
#      run: dotnet restore -p:RestoreUseSkipNonexistentTargets=false -nowarn:msb3202,nu1503
#    - name: Build
#      working-directory: src/core/fuxion
#      run: dotnet build --configuration Release --no-restore
#    - name: Test
      #run: dotnet test --no-restore --verbosity normal

    - name: Pack
      run: dotnet pack --configuration Release --output nupkgs src/Fuxion-pack.sln

    - name: Configure NuGet source
      # Authenticate (if this is the first time) Note you must also pass --store-password-in-clear-text on non-Windows systems.
      #run: dotnet nuget add source https://nuget.pkg.github.com/osjimenez/index.json -n github -u osjimenez -p GH_TOKEN [--store-password-in-clear-text]
      run: dotnet nuget add source https://nuget.pkg.github.com/osjimenez/index.json -n github -u osjimenez -p GH_TOKEN
    
    - name: Publish
      run: dotnet nuget push "src\nupkgs\*.nupkg" --source "github"